fix: NETAPP remove rest EMS vserver find
Use own vserver instead of a random one.

With switching the target/vserver on self.connection it seems like other
requests fail. e.g.:
NetAppDriverException: Volume "sharename" not found
-> Request goes to the wrong vserver

The previous behaviour caused problems with urllib3 and it's connection
pooling/async behaviour and seems to be only copied from the previous
zapi implementation(see nahimsouza's TODO comment from change
I67eb7f6264cf5eea94c0a364082b530b9cdc1ae3).

Closes-Bug: #2101948
Change-Id: I67c1caac8caff339e629e7ba6ee8687c6fd63916
Signed-off-by: Max Lamprecht <max.lamprecht@stackit.cloud>