Restore VMAX unit test mock
Commit If6f7c58f445dd813df7161cc6cd6dd84484e8a7e appears to have
inadvertently removed a mock of get_max_over_subscription_ratio from one
of the test suites. This still passed apparently due to timing of other
test runs also mocking this call, but if tests happen to run in a
differnt order, or if these specific tests are run by themselves, it
results in the error:

TypeError: float() argument must be a string or a number

This restores the mock to match the other tests. These should probably
be refactored to not need this in each one, but this will at least
prevent failures for now and get back to how it had been in prior to the
mentioned change.

Conflicts (due to rebranding):
    cinder/tests/unit/volume/drivers/dell_emc/vmax/test_vmax.py

Change-Id: Iebcc8d8cd9bd39dbde64fef194b262ff7b12e5b6
Signed-off-by: Sean McGinnis <sean.mcginnis@gmail.com>
(cherry picked from commit ec8b8e2a3fb5cf7b947fbe31542493e2c7ebb764)