VNX: Fix issue when creating without type
When creating a volume without type, a error will be thrown:

AttributeError: 'NoneType' object has no attribute 'qos_specs'

This issue was introduced in qos patch:
https://review.openstack.org/#/c/441786/

Change-Id: I861d61dd11f982a8a54b57b6a6c895e6ebe399c0
Closes-bug: #1720063
(cherry picked from commit 5345f8cb9c8ec416aa5d764ea5ea47e3ff4d8d1d)