Replication, hard-coding and dict.name issues in K2
Replication was tested with self-replication due to unavailability
of K2 arrays. Source and target K2 arrays were same.
_delete_volume_replica and _get_replica_status are not working with
different source and target K2 arrays while testing replication.

Hard-coded value of RPO(500) is raising exception while retype:
rpo must be either 1 min or multiple of 5 min

vol_type.name is raising below exception:
AttributeError: 'dict' object has no attribute 'name'

Change-Id: I86e840f9fbc886ef661ddf1de77d433adb901ae5
Closes-Bug: #1612602
Co-Authored-By: VenkataKrishna Reddy <Venkata.Krishna.ctr@kaminario.com>