VNX: fix issue when backing-up in-use volume
When backing-up an in-use volume, initialize_connection_snapshot did not
return connection information for attaching the snapshot thus causing
below error:

TypeError: 'NoneType' object has no attribute '__getitem__'

This commit fixes above issue.

Change-Id: Ie31a0cfe447aee670018914d379d178933437b8c
Closes-bug: #1693956