Fix NoneType has no attribute get error
If volume_type is None and then create volumes with allow-multiattach,
Cinder-schduler will raise error:
AttributeError: 'NoneType' object has no attribute 'get'

Ied42d13b642617dd239ea92c019354b90657821a didn't fix it completely.
The error still exists. Here is the reproduce command:
"cinder create 1 ----allow-multiattach"

Because that the volume_type is always in the "request_spec", if
users doesn't pass it, its value is None.

Change-Id: I1140234dd69a644dcbf6fc3a01f382ee101624b2
Related-bug: #1683431