requirements: Fix duplicate "packaging" entry
We merged a second entry for "packaging" to
requirements.txt, now the requirements-check
gate job is failing with:

ERROR: Package 'packaging' requirement does not match number of lines (1) in openstack/requirements

Change-Id: I3b5c62aa356f6bcffe2d927c18c3b8c24c68ad54
Signed-off-by: Eric Harney <eharney@redhat.com>
(cherry picked from commit cee90b0e496110c48166e0056a908dbb5356ab10)