Fix Snapshot object metadata loading
The Snapshot object will fail to correctly load
metadata.  Initialize the object fully so that
obj_what_changed() works as intended.

This prevents the error:
   AttributeError: 'Snapshot' object has no
   attribute '_obj_metadata'

Closes-Bug: #1805790

Co-Author: Gorka Eguileor <geguileo@redhat.com>
Change-Id: Idee4836ee3e4f9b9f4099e7a1a3d7a4bada3f7b8
(cherry picked from commit 7ad0b0660c819cc7b2909b7e35cbe5a2fe0aef87)
(cherry picked from commit bce461ba43dabea42d5c160ee6ff58298a62bd6c)