Ensure pep8/fast8 run in python 3.6
Running pep8 under py38 is resulting in "AttributeError:
'FlakesChecker' object has no attribute 'CONSTANT'".  The least
intrusive fix seems to be to pin the tox pep8/fast8 testenvs to
python3.6.  Also, keep pycodestyle under 2.6.0 so we don't have to
make any purely stylistic changes in stable/train to get pep8 to
pass.

Change-Id: I17b30c43aa00214d56c51bde3b9d43c0db1695ac