Fix extraneous comma that breaks docbook generation
There is a stray comma in the middle of the help section that changes
the string to a tuple, causing docbook to fail with:

   td.text = "(%s) %s" % (type(option).__name__, option.help.strip())
AttributeError: 'tuple' object has no attribute 'strip'

Change-Id: I8f03801fe5463548e3bba1b13e0370fd30ac9927