Remove superfluous sf_volume_id reassignment
sf_volume_id was being reassigned after a new API call introduced
by a backported fix. This new API call (ModifyVolume) does not
contain the volumeID in its result.

Cloning a volume wasn't possible anymore due to a thrown error:
  KeyError: 'volumeID'

Removing the superfluous reassignment fixes the problem: sf_volume_id
is already assigned with the correct value.

Fixes: bug #1188454
Change-Id: I75196fc68666f28ac6222f43ea2ca6089b782f3f