mypy: Allow mypy to pass with requests-packaged urllib3
mypy fails with:
    error: Module has no attribute "packages"

Set type ignores for requests.packages.urllib3.

Change-Id: I553be293142c3e9525ca9aedfeb1a788830570cb
(cherry picked from commit 54ac21f73b01a671c4e90d707fa2e49b3bf03d54)