Brocade: Fix lookup UnboundLocalError
If we get an exception when getting the southbound client in method
get_device_mapping_from_network we will end up seeing the following
error:

  UnboundLocalError: local variable 'conn' referenced before assignment

This patch fixes this issue by making sure that the conn variable exists
even if that call fails.

TrivialFix
Closes-Bug: #1888550
Change-Id: I621a00d34e9c2b14234e11e94857a39fe54a111f
(cherry picked from commit 122036638d6377f688272ee641e8effbcef933a1)