Fix Google backup driver
Bug #1831735 is not properly fixed and has error
AttributeError: 'bytes' object has no attribute 'encode'.
It is because md5 variable is already bytes object,
so simple removal of problematic line
should do the job.

Related-Bug: #1831735
Change-Id: I2ada405cee25fe8c4dd3777e2c68eacaa7b806c2
Signed-off-by: Roman Hros <roman.hros@dnation.cloud>