Tests: Don't require binding to port 4444
If some other process is listening on port 4444,
test_server_pool_waitall will fail with:

RuntimeError: Could not bind to 127.0.0.1:4444 after
trying for 30 seconds

This test doesn't require use of this specific port,
so let it pick an unused port to avoid this failure.

Closes-Bug: #1421759

Change-Id: I7e6d6f574cd2bbb2fa067001bba4b09b5204a5e1