Backport paramiko 1.8.0 requirement to Folsom.
Require paramiko >= 1.8.0

There is a well-known bug in the Paramiko SSH library that causes
these Exceptions:
SSHException: Error connecting via ssh: PID check failed. RNG must be
re-initialized after fork(). Hint: Try Random.atfork()

This bug has been fixed in Paramiko, and therefore we should require
the newer version for Cinder drivers that use Paramiko to function
properly.

Change-Id: Ia14b7b72393e2a2482ebde418b5477934779bf13
Fixes: bug 1150720