Execute mount.nfs check as root
Currently the existence of 'mount.nfs' is checked with a
non-root user, in this case cinder. This results, for example on SUSE,
in the error:

      NfsException: mount.nfs is not installed

Because mount.nfs is located under /sbin, unprivileged users do not
have /sbin in their PATH to search for executables.
This change switches the parameter run_as_root to true, to find
the binary in privileged directories, as well.

Closes-Bug: #1510150
(cherry picked from commit c811d98c8b3991a9c298fce914f091b2a9ac215f)
(also includes diff from commit 64172b01cd5d8eda3aa282262d7ca060066161d7)

Change-Id: Id1dcc9a7653f1317532da2eb83aa1ecbb5cf5ec8