[SVf]:Fix retype failure for replication volume-type
[Spectrum Virtualize family] While retyping GM to GM or MM to MM or
GMCV to GMCV, chfcmap() call is being made which is resulting in retype
operation failure.
Error: CMMVC7154E The task cannot be completed because the specified
FlashCopy mapping is controlled by a Metro Mirror or Global Mirror
relationship.

chfcmap() should not be called for any FC map which is rc_controlled.
Hence while retyping global mirror to global mirror or
metro mirror to metro mirror or GMCV to GMCV volume, this error comes
up as the FC map of the volume is rc_controlled for these replication
volume-types.

Closes-Bug: #1968159
Change-Id: Ic97a2501b4c895b2b655284bcc320036c2d4e217
(cherry picked from commit b99e73e96cb6448f81a2f4b2e8e624bf36bbff0e)