Fix attach issue for failed-over volume
VNX driver currently doesn't support attaching of failed-over volume,
if user try to do this, a error will pop up like:
    VNXAluNotFoundError: Error: storagegroup command failed

This fix address above issue, user can attach/detach any failed-over
volume.

Closes-bug: 1677956
Change-Id: I7802b7c57e438c27e4df225fb03ca4cda84e2620
(cherry picked from commit ff30688ee5e9e8bc5bc7c1c367bfd0482825586f)